server:
  port: 8080

spring:
  application:
    name: cloud-file-storage

  datasource:
    url: jdbc:postgresql://localhost:5432/storage
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
    change-log: classpath:/migrations/master.xml